baseURL = "/"
languageCode = "zh-CN"
title = "AI工具导航站"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "AI工具导航站"
[params.search]
  enable = true
[params.darkmode]
  enable = false
